blueprint:
  name: Sync Playback between Apple TV and Sonos
  description: "Keep playback in sync between an Apple TV and a Sonos device in the same room. When either device starts playing, the other will automatically pause unless the Sonos Source is set to 'TV' and the option to disable pausing is enabled."
  domain: automation
  input:
    apple_tv_entity:
      name: Apple TV
      description: Select the Apple TV device in the same room.
      selector:
        entity:
          domain: media_player
          integration: apple_tv
    sonos_entity:
      name: Sonos Player
      description: Select the Sonos device in the same room.
      selector:
        entity:
          domain: media_player
          integration: sonos
    disable_pausing_option:
      name: Don't pause either player if Sonos source is TV
      description: "Enable this option if your TV is connected to the Sonos product for its audio output."
      default: false
      selector:
        boolean: {}
  trigger:
    - platform: state
      entity_id: "{{ apple_tv_entity }}"
      from: 'off'
      to: 'playing'
    - platform: state
      entity_id: "{{ sonos_entity }}"
      from: 'off'
      to: 'playing'
  condition:
    - condition: and
      conditions:
        - condition: not
          conditions:
            - condition: state
              entity_id: "{{ sonos_entity }}"
              attribute: source
              state: "TV"
        - condition: state
          entity_id: input_boolean.disable_pausing_option
          state: "off"
  action:
    - service: media_player.media_pause
      target:
        entity_id: "{{ sonos_entity }}"
    - service: media_player.media_pause
      target:
        entity_id: "{{ apple_tv_entity }}"
mode: single
