blueprint:
  name: Sync Pause State Apple TV/Sonos
  description: Synchronizes pause/play state between Apple TV and Sonos player.
  domain: automation
  input:
    sonos_player:
      name: Sonos Player
      description: Select the Sonos player.
      selector:
        entity:
          domain: media_player
          integration: sonos
    apple_tv:
      name: Apple TV
      description: Select the Apple TV device.
      selector:
        entity:
          domain: media_player
          integration: apple_tv
    use_sonos_as_output:
      name: Apple TV uses Sonos as output
      description: Enable this to ensure the Sonos player is not paused when its input is set to "TV".
      selector:
        boolean: {}

trigger:
  - platform: state
    entity_id: !input 'apple_tv'
    from: null
    to: playing
    id: tv_starts_play
  - platform: state
    entity_id: !input 'sonos_player'
    from: null
    to: playing
    id: sonos_starts_play

condition:
  - condition: template
    value_template: >
      {{ not use_sonos_as_output or
         state_attr('input_select.sonos_player', 'source') != 'TV' }}
         
action:
  - if:
      - condition: trigger
        id: tv_starts_play
    then:
      - service: media_player.media_pause
        target:
          entity_id: !input 'sonos_player'
  - if:
      - condition: trigger
        id: sonos_starts_play
    then:
      - service: media_player.media_pause
        target:
          entity_id: !input 'apple_tv'

mode: single
